app_everydefaultfolder:
    Menu:
        Active: true
        Title: 'Default Folders'
        PrimeryMenu: false
        AdminMenu: true
        UserMenu: false
        Controller: 'EveryDefaultFolder'
        Icon: 'fa fa-folder-plus'
EveryDefaultFolder\Model\EveryDefaultFolder:
    API_Filter_DataStoreID_Map: 'RecordSet.DataStoreID'
    API_View_Fields:
        - Slug
        - Active
        - Title
        - RecordSetTitle()
    API_Create_Fields:
        - Slug
        - Active
        - Title
    API_Edit_Fields:
        - Active
        - Title
    API_Dataobject_Allowed_Realations:
        - RecordSet
        - Parent
        - Children
    API_Dataobject_Allowed_Form_Realations:
    API_View_All: true;     
API_Namespace_Class_Map:
    EveryDefaultFolder: 'EveryDefaultFolder\Model\EveryDefaultFolder'

